name: ri-topics
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.1
  - flask-cors=3.0.8
  - hdbscan=0.8.24
  - loguru=0.3.2
  - nltk=3.4.5
  - numba=0.47.0
  - pandas=0.25.3
  - pip=19.3.1
  - pytest=5.3.3
  - pytest-cov=2.8.1
  - python=3.7.5
  - python-dotenv=0.10.3
  - pytorch=1.4.0
  - regex=2019.12.9
  - requests=2.22.0
  - requests-mock=1.7.0
  - scikit-learn=0.22.1
  - scipy=1.3.2
  - spacy=2.2.3
  - tqdm=4.41.1
  - umap-learn=0.3.10
  - pip:
    - schedule==0.6.0
    - sentence-transformers==0.2.5
