name: ri-topics
channels:
  - conda-forge
  - defaults
dependencies:
  - faker=2.0.4
  - flask=1.1.1
  - pip=19.3.1
  - python=3.7.5
  - python-dotenv=0.10.3
  - requests=2.22.0
  - pip:
      - dataclasses-json==0.3.6
