name: ri-topics
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.1
  - hdbscan=0.8.23
  - loguru=0.3.2
  - nltk=3.4.5
  - numba=0.46.0
  - pandas=0.25.3
  - pip=19.3.1
  - pytest=5.3.1
  - pytest-cov=2.8.1
  - python=3.7.5
  - python-dotenv=0.10.3
  - pytorch=1.3.1
  - regex=2019.11.1
  - requests=2.22.0
  - requests-mock=1.7.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - spacy=2.2.3
  - tqdm=4.39.0
  - umap-learn=0.3.10
  - pip:
    - sentence-transformers==0.2.3
