name: ri-topics
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - faker=2.0.4
  - flask=1.1.1
  - nltk=3.4.5
  - pip=19.3.1
  - python=3.7.5
  - python-dotenv=0.10.3
  - pytorch=1.3.1
  - regex=2019.11.1
  - requests=2.22.0
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - spacy=2.2.3
  - tqdm=4.39.0
  - pip:
    - sentence-transformers==0.2.3
